
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 16;
  public static final int NUMS = 3;
  public static final int ELSE = 12;
  public static final int INT = 24;
  public static final int CHAR = 25;
  public static final int WHILE = 9;
  public static final int NOT = 30;
  public static final int END = 7;
  public static final int PARIZQ = 15;
  public static final int PARDER = 18;
  public static final int FUNCTION = 4;
  public static final int TRUE = 13;
  public static final int IF = 11;
  public static final int ID = 28;
  public static final int WRITE = 17;
  public static final int PROGRAM = 5;
  public static final int OPAO = 21;
  public static final int OPMULT = 20;
  public static final int BEGIN = 6;
  public static final int BOOLEAN = 26;
  public static final int COMA = 29;
  public static final int EOF = 0;
  public static final int RECORD = 27;
  public static final int FALSE = 14;
  public static final int ASSIG = 23;
  public static final int error = 1;
  public static final int TEXT = 2;
  public static final int OPSUM = 19;
  public static final int FOR = 8;
  public static final int OPREL = 22;
  public static final int REPEAT = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEXT",
  "NUMS",
  "FUNCTION",
  "PROGRAM",
  "BEGIN",
  "END",
  "FOR",
  "WHILE",
  "REPEAT",
  "IF",
  "ELSE",
  "TRUE",
  "FALSE",
  "PARIZQ",
  "READ",
  "WRITE",
  "PARDER",
  "OPSUM",
  "OPMULT",
  "OPAO",
  "OPREL",
  "ASSIG",
  "INT",
  "CHAR",
  "BOOLEAN",
  "RECORD",
  "ID",
  "COMA",
  "NOT"
  };
}

