
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 4;
  public static final int OPSUM = 20;
  public static final int CHAR = 27;
  public static final int ASSIG = 25;
  public static final int NUMS = 3;
  public static final int REPEAT = 11;
  public static final int INT = 26;
  public static final int FOR = 9;
  public static final int WRITE = 18;
  public static final int NOT = 35;
  public static final int RECORD = 29;
  public static final int BEGIN = 7;
  public static final int OPREL = 24;
  public static final int UNTIL = 32;
  public static final int IF = 12;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 28;
  public static final int PARIZQ = 16;
  public static final int OPAND = 22;
  public static final int TRUE = 14;
  public static final int OPOR = 23;
  public static final int error = 1;
  public static final int PROGRAM = 5;
  public static final int COMA = 34;
  public static final int ELSE = 13;
  public static final int READ = 17;
  public static final int TO = 31;
  public static final int WHILE = 10;
  public static final int THEN = 30;
  public static final int END = 8;
  public static final int TEXT = 2;
  public static final int FALSE = 15;
  public static final int PARDER = 19;
  public static final int OPMULT = 21;
  public static final int DO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEXT",
  "NUMS",
  "FUNCTION",
  "PROGRAM",
  "DO",
  "BEGIN",
  "END",
  "FOR",
  "WHILE",
  "REPEAT",
  "IF",
  "ELSE",
  "TRUE",
  "FALSE",
  "PARIZQ",
  "READ",
  "WRITE",
  "PARDER",
  "OPSUM",
  "OPMULT",
  "OPAND",
  "OPOR",
  "OPREL",
  "ASSIG",
  "INT",
  "CHAR",
  "BOOLEAN",
  "RECORD",
  "THEN",
  "TO",
  "UNTIL",
  "ID",
  "COMA",
  "NOT"
  };
}

